### ISSUE TITLE
Implement "Add Member" functionality for other membership models

### ISSUE THREAD

**Issue by abdelhakeem** [NikhilSharma03/hydra-keys#125]
Implement "Add Member" functionality for other membership models.

You'll mainly modify `AddMemberModal` to account for the current membership model when preparing the transaction.

**Comment by abdelhakeem** [comment]
Update: You'll only have to add NFT member addition support.

**Comment by RajGM** [comment]
Got it.
@abdelhakeem

**Comment by abdelhakeem** [comment]
What is the status of this one?

**Comment by RajGM** [comment]
Hi @abdelhakeem 
I will make a PR for this today.

**Comment by RajGM** [comment]
![wallet](https://user-images.githubusercontent.com/16620150/181259698-4df9435b-5ead-4a87-a734-c7d687e6b5b1.PNG)
wallet object does not any membership object, also we are not providing any GUI options to add different type of membership.

How to differentiate add member for different types of membership models.

**Comment by abdelhakeem** [comment]
> ![wallet](https://user-images.githubusercontent.com/16620150/181259698-4df9435b-5ead-4a87-a734-c7d687e6b5b1.PNG) wallet object does not any membership object, also we are not providing any GUI options to add different type of membership.
> 
> How to differentiate add member for different types of membership models.

In the `hydraWallet` object, there is a `memberShipType` field that holds one of the following values:

- `"Wallet membership"`
- `"NFT membership" `
- `"Token membership" `

https://github.com/NikhilSharma03/hydra-keys/blob/e30e3d556f03ccb9a05d8a13060150c33c6b2db3/components/AddMemberModal.tsx#L23

**Comment by RajGM** [comment]
Hi 
PR made #134
