### ISSUE TITLE
Implement API

### ISSUE THREAD

**Issue by abdelhakeem** [NikhilSharma03/hydra-keys#16]
Implement the API for storing/retrieving values to/from the database to keep track of created wallets, their authorities, and their members.

So far the endpoints we discussed are as follows:

```
POST /api/wallets
(create a <wallet, authority> record in the database)

POST /api/memberships
(create a <wallet, member> record in the database)

GET /api/wallets/[walletPubkey]
(get wallet info, including authority and members)

GET /api/wallets?pubkey=[userPubkey]
(get all wallets where the user is the authority or a member)
```

**Comment by wezn** [comment]
https://docs.google.com/document/d/1d1qzSbSyqnRfEAAjPNPf94DimIf7yXejj3wua7oHAI0/edit?usp=sharing
current api documentation
