### ISSUE TITLE
Send Hydra Wallet Request from frontend to Hydra Program through Hydra SDK

### ISSUE THREAD

**Issue by haianhltr** [NikhilSharma03/hydra-keys#58]
After prepare, serialize, and send transaction from Hydra-Wallet frontend, we with then send it to the Hydra Program and return the following data:

  console.log(fanoutAccount.membershipModel);
  console.log(fanoutAccount.lastSnapshotAmount.toString())
  console.log(fanoutAccount.totalMembers.toString())
  console.log(fanoutAccount.totalInflow.toString())
  console.log(fanoutAccount.totalAvailableShares.toString())
  console.log(fanoutAccount.totalShares.toString());
  console.log(fanoutAccount.name);

**Comment by abdelhakeem** [comment]
Just to make sure everyone is on the same track, we won't be using the Hydra SDK in the backend at all, the backend will simply forward the serialized transaction to the blockchain.

Let's take wallet creation as an example, the following is roughly the flow that would happen:

- Frontend prepares transaction using Hydra SDK
- Frontend serializes transaction
- Frontend sends serialized transaction along with wallet's details as parameters
- API inserts new wallet record in database
- API forwards serialized transaction to blockchain
- If transaction fails, API reverts database changes

**Comment by haianhltr** [comment]
Thank you for your reminder! I will edit the task and use Hydra SDK directly on the frontend

**Comment by haianhltr** [comment]
<img width="1440" alt="Screen Shot 2022-06-26 at 3 29 05 AM" src="https://user-images.githubusercontent.com/91930806/175789593-0bb5b7fc-a003-4e6a-8c03-186d2a62b704.png">

**Comment by haianhltr** [comment]
This function was created inside components/CreateWalletForm. Here are some issues that need to be fixed: 

- Module not found: Can't resolve 'fs': add webpack config to next.config.js
- fanoutSDK required privateKey to be initialized. However I can only derived publicKey using wallet-adapter.
- MembershipModel required an enum type.
- Change to devnet at: hyDQ4Nz1eYyegS6JfenyKwKzYxRsCWCriYSAjtzP4Vg (currently using metaplex and keypair.generate() instead of derived from wallet)

**Comment by Tess99854** [comment]
@haianhltr @abdelhakeem isn't this the same issue referenced in #36 ?

**Comment by haianhltr** [comment]
Yeah, we discussed this 2 days ago. I will also gonna work on this one too

**Comment by haianhltr** [comment]
Okay, I was able to send it to Hydra Program on devnet. What would yall want me to work on next.
