### ISSUE TITLE
Derive privateKey to initialize fanoutSDK function

### ISSUE THREAD

**Issue by haianhltr** [NikhilSharma03/hydra-keys#61]
**Hydra document** 
fanoutSdk = new FanoutClient(
  connection,
  new NodeWallet(new Account(authorityWallet.secretKey))
);

**Mocha test** 
authorityWallet = Keypair.generate();
await airdrop(connection, authorityWallet.publicKey, LAMPORTS_PER_SOL * 10);
fanoutSdk = new FanoutClient(
         connection,
          new NodeWallet(new Account(authorityWallet.secretKey))
);

We need a private key to initialize the fanoutSDK. Then use that constant to create a hydra wallet

**Comment by abdelhakeem** [comment]
You cannot obtain the private key of the user, you basically use the wallet adapter to obtain a `Wallet` object that can sign transactions via the `useAnchorWallet` hook and pass it to the `FanoutClient` constructor instead of `NodeWallet`:

```typescript
const { connection } = useConnection()
const wallet = useAnchorWallet()
```

...and:

```typescript
if (wallet) {
  const fanoutSdk = new FanoutClient(connection, wallet)
  .
  .
  .
}
```

**Comment by haianhltr** [comment]
Thanks! It was very helpful
