### ISSUE TITLE
Set default TotalShares to be 100 for Authority account (?)

### ISSUE THREAD

**Issue by haianhltr** [NikhilSharma03/hydra-keys#62]
Since the authority's TotalShares will always be 100 when we first created the hydra wallet account.

**Comment by abdelhakeem** [comment]
I think the authority is not a member of the wallet by default, also shares are arbitrary numbers not percentages and the total share is not necessarily 100, it is initialized by the wallet creator.

**Comment by Tess99854** [comment]
I will close this issue as it is handled by the wallet creation form, there's no case in which the authority will need a preset number for the total shares
