### ISSUE TITLE
work on the third section of the landing page

### ISSUE THREAD

**Issue by Tess99854** [NikhilSharma03/hydra-keys#7]

**Comment by anshuman-dev** [comment]
Completed a basic Layout.
To Do: Make Carousel.
Addressed by: [#22 ](https://github.com/NikhilSharma03/hydra-keys/pull/22)

**Comment by anshuman-dev** [comment]
@Tess99854 . According to the design, are we looking for a text carousel here?
![Screenshot from 2022-06-15 18-42-59](https://user-images.githubusercontent.com/80671124/173835518-7a594156-0e78-4dea-8f52-d118281aa56f.png)
