### ISSUE TITLE
Validate `Wallet` and `Membership` values on first fetch

### ISSUE THREAD

**Issue by abdelhakeem** [NikhilSharma03/hydra-keys#87]
Validate `Wallet` and `Membership` values (not just their existence on the blockchain) on first fetch, that is when `validated` is `false`

**Comment by NikhilSharma03** [comment]
@abdelhakeem I think I don't quite understand what we have to do here. Can you please elaborate this issue? Thank you.

**Comment by abdelhakeem** [comment]
@NikhilSharma03 Let's take wallets as an example; when the user fetches the details of a wallet for the first time (i.e.: `validated` is `false`), we check (#81) for the existence of the wallet on the blockchain. We do not validate the wallet fields in the database though (e.g.: `totalShares`, `splToken`, etc...). This issue is about validating these fields and updating them if there is a mismatch.

**Comment by abdelhakeem** [comment]
@NikhilSharma03 Typically, you'd branch out from #81 and work on top of it. One way to achieve what is required here is to update [`validateWallet`](https://github.com/NikhilSharma03/hydra-keys/blob/0031f49569702188f9c8cd442e0854d2afdd6014/pages/api/wallets/%5BviewWalletPubkey%5D.ts#L10-L23) to return a `Fanout` object when the wallet exists (actually a `Promise<Fanout>`). And when updating `validated` [here](https://github.com/NikhilSharma03/hydra-keys/blob/0031f49569702188f9c8cd442e0854d2afdd6014/pages/api/wallets/%5BviewWalletPubkey%5D.ts#L63-L75), you would update the other fields as well so that any mismatches are reconciled.
