### ISSUE TITLE
Add wallet native account public key to database.

### ISSUE THREAD

**Issue by abdelhakeem** [NikhilSharma03/hydra-keys#95]
Add the native wallet address on the wallet details page and to the database

**Comment by abdelhakeem** [comment]
@rishabh-vasudevan What is the status of this one?

**Comment by abdelhakeem** [comment]
Okay, so we figured out we actually do not want to store the native account public key as it can be easily derived from the fanout public key which we already have (thanks, @haianhltr): https://github.com/GlassEaters/hydra/blob/main/packages/sdk/src/index.ts#L347-L355

I think this issue can be closed now.

**Comment by rishabh-vasudevan** [comment]
Ok that is nice
